### PR TITLE
Update dependency to xxhash 0.8.0

### PR DESCRIPTION
**Pull request by kakaroto**
Hi,
I'm just looking at xxhash and found your module. While not as popular as the other two options, I like what you're doing, and that your library is up to date and supports XXH3 specifically, which is of interest to me.

I just saw that xxhash 0.8.0 was released a couple of weeks ago with stable xxh3 and xxh128 algorithms. I've updated the dependency to use 0.8.0, changed the expected hash values in the test suite to match the expected values from xxhsum then ran the test, everything worked as expected. I've also updated the README to reflect the stable status of the xxh3/xxh128 algorithms.

See 0.8.0 release notes : https://github.com/Cyan4973/xxHash/releases/tag/v0.8.0

Thanks

### CODE REVIEW

**Comment by ktrongnhan** [comment]
Greetings,

I am whole-heartedly thankful to this PR! It looks great in every aspect to me.
Actually, I was a bit busy recently so sorry for my late reply.

I did receive a notification that xxh3 had reached stable phase and was very excited about that. I definitely put this on my to-dos but you already did it for me.
Nevertheless, I am a bit reluctant to move to 0.8.0. From what I understand, we are very close to the production-ready release of xxHash (v1.0.0) now. So should there be any rush on upgrading?

Thanks,
Nhan

**Comment by kakaroto** [comment]
Hi Nhan,
No problem, I'm busy too and it's taking me a long time to respond to my own PRs as well! :)
I'm using xxHash now on a production server for a product and I need XXH3. Since the algorithm is stable (and hashes are guaranteed to remain the same), I need to use 0.8.0, otherwise all the hashes in my database will be wrong. The hash values already changed between 0.7.1 and 0.8.0, so if I had used that initially, it would have been inconsistent on upgrade and my files wouldn't match what the DB points to anymore.

That's the reason I've needed to upgrade xxhash-addon to the stable release. I can't afford to wait for 1.0.0. (I'm actually pushing my implementation to the production server today).
Thanks.

**Comment by ktrongnhan** [comment]
Marvelous!

I got this PR merged just now. Thanks for your work!
The whole point of this project is to bring xxHash (XXH3 in particular) to the Node.js community. So it is so exciting to know that you are using it for production. That would be awesome if you could share a bit about your project (I can note it in the README.md to provide people with a real use case).

P/S: This is the very first PR from the community. :1st_place_medal:

**Comment by kakaroto** [comment]
Thanks for the merge and congrats on your first community contribution! 🥳 
I don't know if it's worth noting in the README, but my project is a hosting service for Foundry Virtual Tabletop, the site is https://forge-vtt.com and I use XXH3 to hash files on the fly as they are uploaded by users to see if the files are already cached, and I use it to dedup common asset files basically.

**Pull request merged**
